### PR TITLE
Add UITextView+Rx

### PR DESCRIPTION
**Pull request by tokorom**
I would like to add UITextView+Rx has rx_text.
This is retry of https://github.com/kzaher/RxSwift/pull/62.

### CODE REVIEW

**Comment by kzaher** [comment]
Holy shit, this is perfect :bow:

**Comment by tokorom** [comment]
@kzaher I'm sorry that this PR has wasteful diff in `RxAlertViewDelegateProxy.swift`
I`ll try to remove this and reopen!

**Comment by kzaher** [comment]
:bow:

**Comment by tokorom** [comment]
@kzaher I removed the wasteful diff. Please check it https://github.com/kzaher/RxSwift/pull/64 :bow:

**Comment by orta** [comment]
@tokorom - https://nathanhoad.net/git-amend-your-last-commit

**Comment by tokorom** [comment]
@orta Thanks for your teaching!

I tried to use git-amend to this branch https://github.com/tokorom/RxSwift/commits/add-uitextview-rx at that time, but this changes was not reflected to this PR. It might had my procedure :bow:

**Pull request closed without merging**
