### PR TITLE
Use RxMutableBox to workaround compiler bug

### PR DESCRIPTION
**Pull request by shuoli84**
#69 Changes on code template.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @shuoli84,

Awesome job today. 

I've been trying to confirm your solution but unfortunately it still crashes for me in the same configuration iPhone 5S/iOS 7.1 and the codebase that I've sent to you.

The preprocessor code is in the project. If you want to run it, just choose Preprocessor scheme and set first argument to project root and second to some temp directory that preprocessor will use to generate temporary files.

I know this is little ugly for now, but it works.

Maybe you forgot to include some tiny detail?

screen shot 2015-07-28 at 22 35 34

**Comment by shuoli84** [comment]
I also did some other fixes locally, which I thought not related with this. I'll filter out them.

**Comment by shuoli84** [comment]
I just confirmed that Throttle has the same problem in
```swift
    typealias ThrottleState = (
        value: Element?,
        cancellable: SerialDisposable,
        id: UInt64
    )
```
Then I just wrap it with a RxMutableBox, it is fixed. Seems it is not only occurred when mixed. Not sure whether there are some other places needs the fix.

**Comment by kzaher** [comment]
I've just confirmed the fix, awesome work!

I would just have one small request, could you make a PR to develop branch so I can merge this immediately. 

We are using gitflow, so master branch always contains latest released and tested version.

I'll merge this into master in a couple of days when releasing 1.9 version.

:bow:

**Comment by shuoli84** [comment]
Sure. I created a pull request to develop branch. :palm_tree:

**Pull request closed without merging**
